### ISSUE TITLE
Typescript error for v-model in number input (Vue 3)

### ISSUE THREAD

**Issue by ksergazy** [formkit/formkit#950]
### Reproduction

https://formkit.link/b9bffe44886c0b55b23400fc165b308b

### Describe the bug

v-model type for number and other non-string type inputs expect string type in 1.0.0 after upgrading from 0.17.4.

vue-tsc output:
error TS2345
Argument of type '{ type: "number"; name: string; modelValue: number | undefined; validation: string; help: string; }' is not assignable to parameter of type 'FormKitInputs<{ type: "number"; name: string; modelValue: number | undefined; validation: string; help: string; }> & VNodeProps & AllowedComponentProps & ComponentCustomProps'.
  Type '{ type: "number"; name: string; modelValue: number | undefined; validation: string; help: string; }' is not assignable to type 'Omit<Partial<FormKitBaseProps>, "number" | "type" | "value"> & Omit<Partial<FormKitRuntimeProps<{ type: "number"; name: string; modelValue: number | undefined; validation: string; help: string; }>>, "number" | ... 1 more ... | "value"> & ... 5 more ... & ComponentCustomProps'.
    Type '{ type: "number"; name: string; modelValue: number | undefined; validation: string; help: string; }' is not assignable to type 'Omit<Partial<FormKitRuntimeProps<{ type: "number"; name: string; modelValue: number | undefined; validation: string; help: string; }>>, "number" | "type" | "value">'.
      Types of property 'modelValue' are incompatible.
        Type 'number | undefined' is not assignable to type 'string | undefined'.

### Environment

• Vue 3
• FormKit 1.0.0

**Comment by justin-schroeder** [comment]
number inputs do return strings! While it works at runtime, typescript is letting you know that your typing is indeed wrong.

If you’d like to return an actual number you can cast it as such. Checkout the docs here: https://formkit.com/inputs/number#cast-to-number
