### ISSUE TITLE
Autocomplete build issue when upgraded from 0.122.16 to 0.123.1

### ISSUE THREAD

**Issue by paltman** [formkit/formkit#1335]
### Reproduction

n/a

### Describe the bug

When upgrading from 0.122.16 to 0.123.1, all of my autocomplete fields fail to build with this error:

```
error TS2345: Argument of type '{ type: "autocomplete"; innerClass: string; modelValue: any; options: ({ search }: { search: string; }) => Promise<FormKitOptionsList>; optionLoader: (id: string, cachedOption: any) => any; placeholder: string; }' is not assignable to parameter of type 'NonNullable<(Omit<Partial<FormKitBaseProps>, "number" | "type" | "value"> & Omit<Partial<FormKitRuntimeProps<{ type: "autocomplete"; innerClass: string; modelValue: any; options: ({ search }: { ...; }) => Promise<...>; optionLoader: (id: string, cachedOption: any) => any; placeholder: string; }, unknown>>, "number" ...'.
  Types of property 'options' are incompatible.
    Type '({ search }: {    search: string;}) => Promise<FormKitOptionsList>' is not assignable to type 'FormKitOptionsPropWithGroups | undefined'.
```

Snippet from top level component:

```vue
<script lang="ts" setup>
   // ...
   const { searchSalesmen, salesmanLoader } = useSalesmanAutocomplete();
</script>

<template>
   <!-- ... -->
   <FormKit type="autocomplete" inner-class=" bg-white" v-model="salesman" :options="searchSalesmen" :option-loader="salesmanLoader" placeholder="Filter by Salesman" />
</template>
```

useSalesmanAutocomplete:

```js
export const useSalesmanAutocomplete = (salesman?: Ref<Salesman | null>) => {
  const _formatRecord = (item: SalesmanItemFragment) => ({
    value: item.id,
    label: item.salesmanName,
  });

  const _extract = (data: SalesmenQuery) => data.salesmen;

  const { createSearch, loader } = useAutocomplete(SALESMEN_QUERY, _formatRecord, _extract, salesman);

  return {
    searchSalesmen: createSearch((search: string) => ({ query: search })),
    salesmanLoader: loader,
  }
};
```

useAutocomplete:

```js
import { Ref } from 'vue';
import { useQuery, provideApolloClient } from '@vue/apollo-composable';
import { client } from '@/apolloClients';

import { promisify } from '@/utils/promises';

import { TypedDocumentNode } from '@apollo/client';


export default (query: TypedDocumentNode, recordFormatter: Function, extract: Function, defaultObj?: Ref) => {
  const _transform = (data: any) => extract(data)
    .map((record: any) => recordFormatter(record));

  const loader = (id: string, cachedOption: any) => {
    if (cachedOption || !defaultObj?.value) return cachedOption;
    return recordFormatter(defaultObj.value);
  };

  const createSearch = (searchOverride?: Function, cache: boolean = true) => {
    return ({ search }: { search: string }) => {
      const defaultArgs = { filters: { query: search || '' } };
      const override = searchOverride ? searchOverride(search) : null;
      const { onResult } = provideApolloClient(client)(() => useQuery(query, { ...(override || defaultArgs) }, {
        fetchPolicy: cache ? 'cache-first' : 'network-only',
      }));
      return promisify(onResult, _transform);
    };
  };

  return {
    createSearch,
    loader,
  };
};
```

promisify:

```js
import { FormKitOptionsList } from '@formkit/inputs';

export const promisify = (onResult: Function, convert: Function) => new Promise<FormKitOptionsList>((resolve, reject) => {
  onResult((r: any) => {
    if (r.loading) return;
    if (r.data) {
      resolve(convert(r.data));
    } else {
      reject(r.errors);
    }
  });
});
```

### Environment

pro 0.123.1

**Comment by sashamilenkovic** [comment]
@paltman Hey there! This should be resolved at FormKit Pro v0.123.2. I'll leave this open until we hear back from you.

**Comment by paltman** [comment]
Fixed!  Thanks!
